language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer install --no-interaction

script: vendor/bin/phpunit
