language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - setup=basic
    - APP_ENV=testing

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi

script: vendor/bin/phpunit
